# Generated by Django 4.2 on 2025-11-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VAL_TIPO_PARTO', 'Tipo de Parto'), ('VAL_SEXO_RN', 'Sexo Recién Nacido'), ('VAL_CONSULTORIO', 'Consultorios'), ('VAL_REANIMACION', 'Reanimación RN'), ('VAL_POSICION_MATERNA', 'Posición Materna'), ('VAL_ACOMPANANTE', 'Acompañante'), ('VAL_INICIO_TRABAJO_PARTO', 'Inicio Trabajo de Parto'), ('VAL_MANEJO_DOLOR', 'Manejo del Dolor'), ('VAL_POSICION_EXPULSIVO', 'Posición Expulsivo'), ('VAL_DESTINO_RN', 'Destino Recién Nacido'), ('VAL_RESULTADO_TAMIZAJE', 'Resultado Tamizaje'), ('VAL_VACUNA', 'Vacunas'), ('VAL_ROBSON_GRUPO', 'Grupos de Robson'), ('VAL_PROFILAXIS_RN', 'Profilaxis Recién Nacido')], help_text='Grupo al que pertenece el valor (ej. VAL_SEXO_RN)', max_length=50)),
                ('valor', models.CharField(help_text='Valor a mostrar en la lista (ej. FEMENINO)', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Ítem activo y visible en los formularios')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en la lista')),
            ],
            options={
                'verbose_name': 'Valor de Catálogo',
                'verbose_name_plural': 'Maestro de Catálogos',
                'ordering': ['tipo', 'orden', 'valor'],
                'unique_together': {('tipo', 'valor')},
            },
        ),
    ]
