# Generated by Django 4.2 on 2025-11-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_catalogo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='tipo',
            field=models.CharField(choices=[('VAL_TIPO_PARTO', 'Tipo de Parto'), ('VAL_ESTABLECIMIENTO', 'Establecimientos de Salud'), ('VAL_SEXO_RN', 'Sexo Recién Nacido'), ('VAL_CONSULTORIO', 'Consultorios'), ('VAL_REANIMACION', 'Reanimación RN'), ('VAL_POSICION_MATERNA', 'Posición Materna'), ('VAL_ACOMPANANTE', 'Acompañante'), ('VAL_INICIO_TRABAJO_PARTO', 'Inicio Trabajo de Parto'), ('VAL_MANEJO_DOLOR', 'Manejo del Dolor'), ('VAL_POSICION_EXPULSIVO', 'Posición Expulsivo'), ('VAL_DESTINO_RN', 'Destino Recién Nacido'), ('VAL_RESULTADO_TAMIZAJE', 'Resultado Tamizaje'), ('VAL_VACUNA', 'Vacunas'), ('VAL_ROBSON_GRUPO', 'Grupos de Robson'), ('VAL_PROFILAXIS_RN', 'Profilaxis Recién Nacido'), ('VAL_COMUNA', 'Comuna')], help_text='Grupo al que pertenece el valor (ej. VAL_SEXO_RN)', max_length=50),
        ),
    ]
