# Generated by Django 4.2 on 2025-11-14 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('comuna', models.CharField(max_length=100)),
                ('cesfam', models.CharField(max_length=100)),
                ('migrante', models.BooleanField(default=False)),
                ('pueblo_originario', models.BooleanField(default=False)),
                ('discapacidad', models.BooleanField(default=False)),
                ('documentos', models.JSONField(blank=True, default=dict, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ficha Madre',
                'verbose_name_plural': 'Fichas Madres',
            },
        ),
        migrations.CreateModel(
            name='TamizajeMaterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdrl_resultado', models.CharField(max_length=50)),
                ('vdrl_tratamiento', models.BooleanField(default=False)),
                ('vih_resultado', models.CharField(max_length=50)),
                ('hepb_resultado', models.CharField(max_length=50)),
                ('profilaxis_vhb_completa', models.BooleanField(default=False)),
                ('madre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tamizaje', to='madre.madre')),
            ],
            options={
                'verbose_name': 'Tamizaje Materno (REM A11)',
                'verbose_name_plural': 'Tamizajes Maternos (REM A11)',
            },
        ),
        migrations.CreateModel(
            name='MadreObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('firma_simple', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obs_madre', to=settings.AUTH_USER_MODEL)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='madre.madre')),
            ],
            options={
                'verbose_name': 'Observación de Madre',
                'verbose_name_plural': 'Observaciones de Madre',
                'ordering': ['-fecha'],
            },
        ),
    ]
