# Generated by Django 4.2 on 2025-11-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madre',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='documentos_madre/'),
        ),
    ]
