# Generated by Django 4.2 on 2025-11-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_catalogo_tipo'),
        ('madre', '0002_alter_madre_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madre',
            name='cesfam',
            field=models.ForeignKey(limit_choices_to={'tipo': 'VAL_ESTABLECIMIENTO'}, on_delete=django.db.models.deletion.PROTECT, related_name='madres_cesfam', to='catalogo.catalogo'),
        ),
        migrations.AlterField(
            model_name='madre',
            name='comuna',
            field=models.ForeignKey(limit_choices_to={'tipo': 'VAL_COMUNA'}, on_delete=django.db.models.deletion.PROTECT, related_name='madres_comuna', to='catalogo.catalogo'),
        ),
    ]
