# Generated by Django 4.2 on 2025-11-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madre', '0004_defuncionmadre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='madre',
            options={'ordering': ['-id'], 'verbose_name': 'Ficha Madre', 'verbose_name_plural': 'Fichas Madres'},
        ),
        migrations.AddField(
            model_name='tamizajematerno',
            name='chagas_resultado',
            field=models.CharField(blank=True, default='PENDIENTE', max_length=50),
        ),
    ]
