# Generated by Django 4.2 on 2025-11-15 01:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parto', '0001_initial'),
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('I', 'Indeterminado')], max_length=1)),
                ('peso', models.PositiveSmallIntegerField(verbose_name='Peso (gramos)')),
                ('talla', models.PositiveSmallIntegerField(verbose_name='Talla (cm)')),
                ('pc', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Perímetro Craneano (cm)')),
                ('apgar_1', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='APGAR al 1er minuto')),
                ('apgar_5', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='APGAR a los 5 minutos')),
                ('reanimacion_basica', models.BooleanField(default=False, verbose_name='Reanimación Básica')),
                ('reanimacion_avanzada', models.BooleanField(default=False, verbose_name='Reanimación Avanzada')),
                ('clampeo_tardio', models.BooleanField(default=False, verbose_name='Clampeo Tardío de Cordón')),
                ('lactancia_60min', models.BooleanField(default=False, verbose_name='Inicio Lactancia < 60 min')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_creados', to=settings.AUTH_USER_MODEL)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recien_nacidos', to='parto.parto')),
            ],
            options={
                'verbose_name': 'Recién Nacido',
                'verbose_name_plural': 'Recién Nacidos',
                'ordering': ['-parto__fecha'],
            },
        ),
        migrations.CreateModel(
            name='RNObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Observación / Diagnóstico')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('firma_simple', models.BooleanField(default=False, verbose_name='Firmado')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_rn_escritas', to=settings.AUTH_USER_MODEL)),
                ('rn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='recien_nacido.reciennacido')),
            ],
            options={
                'verbose_name': 'Observación de RN',
                'verbose_name_plural': 'Observaciones de RN',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProfiRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora de Administración')),
                ('profesional', models.CharField(max_length=255, verbose_name='Profesional que administra')),
                ('reaccion_adversa', models.TextField(blank=True, null=True, verbose_name='Reacción Adversa (si aplica)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profilaxis_registradas', to=settings.AUTH_USER_MODEL)),
                ('rn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilaxis_set', to='recien_nacido.reciennacido')),
                ('tipo', models.ForeignKey(limit_choices_to={'activo': True, 'tipo': 'PROFILAXIS_RN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profilaxis_aplicadas', to='catalogo.catalogo')),
            ],
            options={
                'verbose_name': 'Profilaxis de RN',
                'verbose_name_plural': 'Profilaxis de RN',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
