# Generated by Django 4.2 on 2025-11-15 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('recien_nacido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profirn',
            name='tipo',
            field=models.ForeignKey(limit_choices_to={'activo': True, 'tipo': 'VAL_PROFILAXIS_RN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profilaxis_aplicadas', to='catalogo.catalogo'),
        ),
    ]
