# Generated by Django 4.2 on 2025-11-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recien_nacido', '0002_alter_profirn_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciennacido',
            name='fecha_alta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Alta (Egreso)'),
        ),
    ]
