# Generated by Django 4.2 on 2025-11-20 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recien_nacido', '0003_reciennacido_fecha_alta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefuncionRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('razon', models.TextField()),
                ('rn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defunciones', to='recien_nacido.reciennacido')),
                ('usuario_registra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Defunción de Recién Nacido',
                'verbose_name_plural': 'Defunciones de Recién Nacidos',
            },
        ),
    ]
