# Generated by Django 4.2 on 2025-11-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_twofactorcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('ti_informatica', 'TI / Informática'), ('profesional_salud', 'Profesional Salud'), ('tecnico_salud', 'Técnico Salud'), ('administrativo', 'Administrativo')], default='administrativo', max_length=20),
        ),
    ]
