# Generated by Django 4.2 on 2025-11-14 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('madre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_parto', models.CharField(max_length=100)),
                ('edad_gestacional_semanas', models.IntegerField()),
                ('establecimiento', models.CharField(max_length=100)),
                ('acompanamiento_trabajo_parto', models.BooleanField(default=False)),
                ('acompanamiento_solo_expulsivo', models.BooleanField(default=False)),
                ('piel_piel_madre_30min', models.BooleanField(default=False)),
                ('piel_piel_acomp_30min', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='madre.madre')),
            ],
            options={
                'verbose_name': 'Registro de Parto',
                'verbose_name_plural': 'Registros de Partos',
            },
        ),
        migrations.CreateModel(
            name='RobsonParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=10)),
                ('cesarea_electiva', models.BooleanField(default=False)),
                ('cesarea_urgencia', models.BooleanField(default=False)),
                ('parto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_robson', to='parto.parto')),
            ],
            options={
                'verbose_name': 'Clasificación Robson',
                'verbose_name_plural': 'Clasificaciones Robson',
            },
        ),
        migrations.CreateModel(
            name='PartoObservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('firma_simple', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obs_parto', to=settings.AUTH_USER_MODEL)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='parto.parto')),
            ],
            options={
                'verbose_name': 'Observación de Parto',
                'verbose_name_plural': 'Observaciones de Parto',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ModeloAtencionParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libertad_movimiento', models.BooleanField(default=False)),
                ('regimen_hidrico_amplio', models.BooleanField(default=False)),
                ('manejo_dolor', models.CharField(max_length=100)),
                ('posicion_expulsivo', models.CharField(max_length=100)),
                ('parto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modelo_atencion', to='parto.parto')),
            ],
            options={
                'verbose_name': 'Modelo de Atención del Parto (REM A21)',
                'verbose_name_plural': 'Modelos de Atención del Parto (REM A21)',
            },
        ),
    ]
