# Generated by Django 4.2 on 2025-11-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoParto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Parto',
                'verbose_name_plural': 'Tipos de Parto',
            },
        ),
        migrations.AlterField(
            model_name='parto',
            name='tipo_parto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='parto.tipoparto'),
        ),
    ]
