# Generated by Django 4.2 on 2025-11-16 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('parto', '0002_tipoparto_alter_parto_tipo_parto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parto',
            name='tipo_parto',
            field=models.ForeignKey(limit_choices_to={'tipo': 'VAL_TIPO_PARTO'}, on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='catalogo.catalogo', verbose_name='Tipo de Parto'),
        ),
        migrations.DeleteModel(
            name='TipoParto',
        ),
    ]
