# Generated by Django 4.2 on 2025-11-16 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_catalogo_tipo'),
        ('parto', '0003_alter_parto_tipo_parto_delete_tipoparto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parto',
            name='establecimiento',
            field=models.ForeignKey(limit_choices_to={'tipo': 'VAL_ESTABLECIMIENTO'}, on_delete=django.db.models.deletion.PROTECT, related_name='partos_establecimiento', to='catalogo.catalogo', verbose_name='Establecimiento'),
        ),
    ]
