# Generated by Django 4.2 on 2025-11-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parto', '0004_alter_parto_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='gemelos',
            field=models.BooleanField(default=False, verbose_name='Gemelos'),
        ),
    ]
